repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        language_version: python3
        stages: [commit]
#         files: ^backend/  # Specify the backend directory
#         types: [python]
#         stages: [commit]  # This fixes the invalid 'pre-commit' stage