version: '3.8'

services:

  try-demo-db:
    build: ./database/postgres
    image: ${DOCKER_REGISTRY:-localhost}/data-dialogue-postgres:${TAG:-latest}
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - try_on_data:/var/lib/postgresql/data
    command: >
      bash -c "
        echo 'Starting PostgreSQL and initialization script...';
        docker-entrypoint.sh postgres &
        until pg_isready -U demo -d dvdrental; do
          echo 'Waiting for PostgreSQL to start...';
          sleep 2;
        done;
        echo 'PostgreSQL is ready. Running initialization script...';
        bash /docker-entrypoint-initdb.d/load-dvd-rental-db.sh;
        echo 'Initialization complete. Keeping container running...';
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d dvdrental"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-localhost}/data-dialogue-backend:${TAG:-latest}
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - models:/data/models

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY:-localhost}/data-dialogue-frontend:${TAG:-latest}
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - try-demo-db
      - backend

volumes:
  try_on_data:
  models:

networks:
  default:
    name: data-dialogue-network
    driver: bridge