version: '1.0'

services:
  postgres:
    build: ./database/postgres
    environment:
      POSTGRES_DB: dvd_db
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo -d dvd_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - MODEL_REPO=${MODEL_REPO}
        - MODEL_FILE=${MODEL_FILE}
        - MODEL_LOCAL_DIR=${MODEL_LOCAL_DIR}
    env_file:
      - .env
    environment:
      - MODEL_REPO=${MODEL_REPO}
      - MODEL_FILE=${MODEL_FILE}
      - MODEL_LOCAL_DIR=${MODEL_LOCAL_DIR}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  default:
    name: data-dialogue-network
    driver: bridge