name: Docker Compose Build and Push

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - master
  workflow_dispatch:  # For manual triggering

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        run: |
          # Define image names
          BACKEND_IMAGE="${{ secrets.DOCKER_REGISTRY }}/data-dialogue-backend:${{ steps.vars.outputs.SHORT_SHA }}"
          FRONTEND_IMAGE="${{ secrets.DOCKER_REGISTRY }}/data-dialogue-frontend:${{ steps.vars.outputs.SHORT_SHA }}"
          
          # Build images
          docker-compose build \
            --build-arg BACKEND_IMAGE=${BACKEND_IMAGE} \
            --build-arg FRONTEND_IMAGE=${FRONTEND_IMAGE}
          
          # Push images
          docker push ${BACKEND_IMAGE}
          docker push ${FRONTEND_IMAGE}
          
          # Tag and push latest for master branch
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            docker tag ${BACKEND_IMAGE} "${{ secrets.DOCKER_REGISTRY }}/data-dialogue-backend:latest"
            docker tag ${FRONTEND_IMAGE} "${{ secrets.DOCKER_REGISTRY }}/data-dialogue-frontend:latest"
            docker push "${{ secrets.DOCKER_REGISTRY }}/data-dialogue-backend:latest"
            docker push "${{ secrets.DOCKER_REGISTRY }}/data-dialogue-frontend:latest"
          fi

      - name: Print debug information
        run: |
          echo "Docker Registry: ${{ secrets.DOCKER_REGISTRY }}"
          echo "Short SHA: ${{ steps.vars.outputs.SHORT_SHA }}"
          echo "Backend Image: ${{ secrets.DOCKER_REGISTRY }}/data-dialogue-backend:${{ steps.vars.outputs.SHORT_SHA }}"
          echo "Frontend Image: ${{ secrets.DOCKER_REGISTRY }}/data-dialogue-frontend:${{ steps.vars.outputs.SHORT_SHA }}"
