name: CD Pipeline

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main
  workflow_dispatch:  # For manual triggering

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate version
        id: version
        run: |
          if [[ -z "${{ github.base_ref }}" ]]; then
              # For non-main branches, use a development version
              short_sha=$(git rev-parse --short HEAD)
              echo "VERSION=dev-$short_sha" >> $GITHUB_OUTPUT
          elif [[ "${{ github.base_ref }}" == "main" ]]; then
            # Get the latest tag
            latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
            # Increment the patch version
            new_tag=$(echo $latest_tag | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
            echo "VERSION=$new_tag" >> $GITHUB_OUTPUT
          else
            # For non-main branches, use a development version
            short_sha=$(git rev-parse --short HEAD)
            echo "VERSION=dev-$short_sha" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
